baseURL = "https://blog.zburu.com"
languageCode = "en-us"
title = "子舒的博客"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "zburu"
  homepage = "/"

[languages]
  [languages.cn]
    contentDir = "content"
    languageName = "Chinese"
    weight = 1


[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "周刊"
link = "/161"


[[params.socials]]
name = "关于"
link = "/2"
