baseURL = "https://blog.zburu.com"
languageCode = "en-us"
title = "子舒的博客"
theme = "yinyang"

paginate = 5

summaryLength = 140

[params]
  title = "子舒的博客"
  Description = "基于hugo搭建的静态博客，作为zburu.com的备份"
  favicon = "https://oss.zburu.com/favicon.ico"


[author]
  name = "子舒"
  homepage = "/"

[[params.socials]]
name = "RSS"
link = "/index.xml"



[[params.socials]]
name = "留言"
link = "/message"

[[params.socials]]
name = "周刊"
link = "/weekly"


[[params.socials]]
name = "关于"
link = "/about"

[permalinks]
  posts = "/posts/:slug.html"